name: Publish to PyPI

on:
  release:
    types: [published, prereleased]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run tests
      run: |
        pytest

  build-and-publish:
    needs: test
    name: Build and publish
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.release.prerelease && 'testpypi' || 'pypi' }}
      url: ${{ github.event.release.prerelease && 'https://test.pypi.org/p/wp-engine-api' || 'https://pypi.org/p/wp-engine-api' }}
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish to TestPyPI
      if: github.event.release.prerelease
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    - name: Publish to PyPI
      if: ${{ !github.event.release.prerelease }}
      uses: pypa/gh-action-pypi-publish@release/v1
